### ISSUE TITLE
Original source maps may not be uploaded at all

### ISSUE THREAD

**Issue by phcoliveira** [jscrambler/jscrambler#6]
Hello again. I opened this issue on `jscrambler/ember-cli-jscrambler`, but it appears unseen.

After the release of the version `5.2.3`, `ember-cli-deploy-bugsnag` uploads all source maps correctly, leading me to believe it didn't work before due [this bug in version `5.2.2`](https://github.com/jscrambler/jscrambler/issues/4).

But the final source maps, for the protected and minified files, recreate the original compilations from Babel, transpilled from ES6 to ES5. I had the impression that the original source maps, for the development files written in ES6, should be merged to the final one, according to [Jscrambler's docs](https://docs.jscrambler.com/code-integrity/documentation/source-maps/api).

I think the original source maps, for the development files in ES6, are note being uploaded at all. What makes me think that is Jscrambler's assumption for the file paths of a given source map and its correlated Javascript file. According to the docs, if a Javascript file has a path given by `assets/application.js`, its correlated source map should have a path of `assets/application.js.map` in order to be automatically uploaded to be merged into the final source map, for the protected file.

The problem with this approach is that Ember-CLI offers no way for customizing the file path of a source map. Even after disabling the `fingerprint` option in `ember-cli-build`, which naturally breaks Jscrambler's assumption, we would have the pair `assets/application.js` and `assets/application.map`.

Am I right to assume the final source map trace the errors back to the concatenated, transpilled application file because the original source maps are not being uploaded at all?

**Comment by joaosamouco** [comment]
Hi @phcoliveira.

You are right to assume that the original source maps (the ones that point to the original ES6 code) are not being uploaded to Jscrambler. Unfortunately, there is nothing we can do to fix it since this is likely an issue with `embler-cli-babel` that's not returning the right source maps.
You can try it yourself by disabling Jscrambler in your project and you will see that the source maps still won't point to the original ES6 code.

Jscrambler will merge source maps with the ones produced by `ember-cli-babel` and since those are not pointing to the ES6 code, Jscrambler won't be able to do it also.

**Comment by phcoliveira** [comment]
@joaosamouco, thanks for your replay. I will check this out and try to determine if `ember-cli-babel` can, indeed, point to the original ES6 files.

Nevertheless, I don't think the both of us are being clear enough, as you said it yourself that the original source maps are not being uploaded to Jscrambler. I think what you meant is: "the original source maps are being uploaded to Jscrambler, but they do not point to the development files."

In order to Jscrambler merge previous source maps, `jscrambler-cli` needs to upload a Javascript file, to be protected, and its correlated source map, to be merged into the final source map. But `jscrambler-cli` expects a pair of files named as such:

- `application.js`
- `application.js.map`

But even if we disable fingerprinting, `ember-cli` would produce a pair of files named as these:

- `application.js`
- `application.map`

See the difference? I think `jscrambler-cli` is not uploading the first source map to be merged because it expects a file named `application.js.map`, although `ember-cli` names it `application.map`.

**Comment by joaosamouco** [comment]
Yes, that's actually what I meant to say. `"the original source maps are being uploaded to Jscrambler, but they do not point to the development files."`

We are handling that case in our `ember-cli` plugin. If you log in to your account and check your application, you can see on the file tree that the correct source map was uploaded. You can even download the `zip` file it will include the source map that was upload and you will see that is the correct one.

So even though `ember` produces an `application.map` instead of `application.js.map`, we are uploading it properly on our `ember-cli-jscrambler`.

**Comment by phcoliveira** [comment]
@joaosamouco, your confirmation on the automatic uploading of the original source files, despite the assumption for the pair of files, made me look for alternative reasons.

I got the original source maps, for the unprotected files, to recreate the original development files in ES6. Jscrambler, accordingly, merges these files and we finally ended up having Bugsnag to trace errors back to development files.

All you have to do is set this option in `ember-cli-build.js`:
```
sourcemaps: {
  enabled: true,
  extensions: ['js']
},

babel: {
  sourceMaps: 'inline'
}
```
